# 服务器端口-部署
server:
  port: 9091
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /maskdemoserver
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
    aop:
      proxy-target-class: true
    jackson:
      time-zone: GMT+8
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/maskdemo?characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password:
    #连接池
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  jmx:
    enabled: true
logging:
  level: debug

wx:
  appid: wx42b3ddfdc238f513
  appsecret: 225d6ce0685cd60fafed0c0f32d92863